# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalog:
    container_name: 'catalog'
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      MongoDbSettings__Host: mongo
      MongoDbSettings__User: mongoadmin 
      # not ideal but okay for testing purposes
      MongoDbSettings__Password: password
    ports:
      - 8081:80
    depends_on:
      - db

  db:
    image: mongo
    container_name: 'mongo'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      # not ideal but okay for testing purposes
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata: